use ProjetoCRM

CREATE TABLE Users (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(150) NOT NULL,
	Email NVARCHAR(254) NOT NULL UNIQUE,
	Password NVARCHAR(255) NOT NULL,
	IsActive BIT NOT NULL DEFAULT 1,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME NULL,

	CONSTRAINT FK_Specialists_Users
		FOREIGN KEY (UserId)
		REFERENCES Users(ID)
);

CREATE TABLE Specialists (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(150) NOT NULL,
	UserId INT NULL,
	IsActive BIT NOT NULL DEFAULT 1,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME NULL,

	CONSTRAINT FK_Specialists_Users
		FOREIGN KEY (UserId)
		REFERENCES Users(ID)
);

CREATE TABLE Clients (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(150) NOT NULL,
	Email NVARCHAR(254) NULL,
	PhoneNumber NVARCHAR(20) NULL,
	IsActive BIT NOT NULL DEFAULT 1,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME NULL
);
